### ISSUE TITLE
BUG: LSE is not correctly aligned

### ISSUE THREAD

**Issue by XCZhang03** [YWolfeee/Training-Free-Guidance#1]
Steps to reproduce the bug:
Hardware: NVIDIA GeForce RTX 3090
run `bash scripts/style_transfer.sh`
output:
`/workspace/zhangxiangcheng/miniconda3/envs/TFG/lib/python3.10/site-packages/diffusers/models/attention_processor.py:1244: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::_scaled_dot_product_efficient_attention. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  hidden_states = F.scaled_dot_product_attention(
  0%|                                                                   | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/zhangxiangcheng/code/exp/consistency_guidance/TFG/main.py", line 23, in <module>
    samples = pipeline.sample(args.num_samples)
  File "/workspace/zhangxiangcheng/code/exp/consistency_guidance/TFG/pipeline.py", line 29, in sample
    samples = self.network.sample(sample_size=sample_size, guidance=self.guider)
  File "/workspace/zhangxiangcheng/miniconda3/envs/TFG/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/zhangxiangcheng/code/exp/consistency_guidance/TFG/diffusion/stable_diffusion.py", line 131, in sample
    latents = guidance.guide_step(
  File "/workspace/zhangxiangcheng/code/exp/consistency_guidance/TFG/methods/tfg.py", line 105, in guide_step
    Delta_t = grad(logprobs.sum(), x_g)[0]
  File "/workspace/zhangxiangcheng/miniconda3/envs/TFG/lib/python3.10/site-packages/torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: LSE is not correctly aligned`

Likely due to the bad implementation of the attention mechanism.

**Comment by nktoan** [comment]
Hi @MaydaY-Tsinghua @YWolfeee , have you resolved the problem?

Thanks.

**Comment by gaoxin492** [comment]
I encountered the same problem. It seems to be due to the dimension mismatch. The shape of the input in the latent space is [B, 4, 64, 64], while Style Clip uses vit-16 and the acceptable image size is [B, 3, 224, 224] in the pixel space. I wonder if you have solved this problem? @MaydaY-Tsinghua

**Comment by linhaowei1** [comment]
Hi everyone,

We sincerely apologize for the inconvenience caused by this bug. Recently, we refactored the TFG codebase to leverage `torch.vmap`, but it appears we didn’t test it thoroughly.

To temporarily resolve this issue, please update the code in lines 21–27 of `methods/tfg.py` with the following snippet:

```python
flat_x0 = (x0[None] + mc_eps).reshape(-1, *x0.shape[1:])
outs = self.guider.get_guidance(flat_x0, return_logp=True, check_grad=False, **kwargs)
```

We are working on a fix and will release an update soon. Thank you for bringing this to our attention and for your understanding.

**Comment by gaoxin492** [comment]
@linhaowei1 Thanks so much for your quick response! After tweaking lines 21-26, the style transfer task is running smoothly now. I realized I made a mistake earlier when I mentioned the image dimensions as [B, 4, 64, 64]; I forgot about the post-processing step in the style guider.

**Comment by nktoan** [comment]
Hi @linhaowei1 @gaoxin492 ,

Have you tried the label guidance task on CIFAR-10 with the suggested modified code? It appears that:  

```python
flat_x0 = (x0[None] + mc_eps).reshape(-1, *x0.shape[1:])
outs = self.guider.get_guidance(flat_x0, return_logp=True, check_grad=False, **kwargs)
```

significantly reduces performance compared to using `torch.vmap`. Have you encountered the same issue?

**Comment by gaoxin492** [comment]
@nktoan @linhaowei1 Yes, I also tested the label guidance task. When using `torch.vmap`, the evaluation results were as follows (`torch.vmap` works for this task but not for style transfer):
{'inception_score': 3.278809, 'fid': 97.89599438609466, 'validity': 0.8359375, 'validity_resnet_cifar10.pt': 0.8359375}.

However, after replacing lines 21–27 of the code and keeping all other parameters unchanged, the performance dropped to:
{'inception_score': 5.8543544, 'fid': 203.66262459275603, 'validity': 0.125, 'validity_resnet_cifar10.pt': 0.125}.

I’m not sure why this happens. Do you have any insights?

**Comment by linhaowei1** [comment]
> @nktoan @linhaowei1 Yes, I also tested the label guidance task. When using `torch.vmap`, the evaluation results were as follows (`torch.vmap` works for this task but not for style transfer): {'inception_score': 3.278809, 'fid': 97.89599438609466, 'validity': 0.8359375, 'validity_resnet_cifar10.pt': 0.8359375}.
> 
> However, after replacing lines 21–27 of the code and keeping all other parameters unchanged, the performance dropped to: {'inception_score': 5.8543544, 'fid': 203.66262459275603, 'validity': 0.125, 'validity_resnet_cifar10.pt': 0.125}.
> 
> I’m not sure why this happens. Do you have any insights?

Apologies again for the oversight earlier! I realized that the `avg_logprobs` computation also requires reshaping.
Here’s the revised code snippet that works for me:

```python
flat_x0 = (x0[None] + mc_eps).reshape(-1, *x0.shape[1:])
outs = self.guider.get_guidance(flat_x0, return_logp=True, check_grad=False, **kwargs)

avg_logprobs = torch.logsumexp(outs.reshape(mc_eps.shape[0], x0.shape[0]), dim=0) - math.log(mc_eps.shape[0])
```

Let me know if you have thoughts or further suggestions!

**Comment by gaoxin492** [comment]
@linhaowei1 Thank you very much for your prompt response. The evaluation results are now consistent, whether using `torch.vmap` or not.

**Comment by linhaowei1** [comment]
> @linhaowei1 Thank you very much for your prompt response. The evaluation results are now consistent, whether using `torch.vmap` or not.

Glad to hear that! I’ve made a new commit to address this bug.
